apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: cluster-ebsco
  project: cs-team
spec:
  blueprint:
    name: minimal
  config:
    autoApproveNodes: true
    installerTtl: 365
    kubernetesVersion: v1.30.4
    network:
      cni:
        name: Calico
        version: 3.28.1
      podSubnet: 10.244.0.0/16
      serviceSubnet: 10.96.0.0/12
    nodes:
    - arch: amd64
      hostname: instance-20241024-1648-akhil
      operatingSystem: Ubuntu22.04
      privateIP: 10.0.0.82
      roles:
      - ControlPlane
      - Worker
  proxy: {}
  type: mks
