apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  labels:
    test: ""
  name: new-mm-test-cluster
  project: cs-team
spec:
  blueprintConfig:
    name: minimal
    version: 2.10.0
  cloudCredentials: akhil-eks-role
  config:
    addons:
    - name: coredns
      version: v1.11.1-eksbuild.8
    - name: vpc-cni
      version: v1.18.1-eksbuild.3
    - name: kube-proxy
      version: v1.30.0-eksbuild.3
    - name: aws-ebs-csi-driver
      version: latest
    managedNodeGroups:
    - amiFamily: AmazonLinux2
      desiredCapacity: 2
      iam:
        withAddonPolicies:
          autoScaler: true
      instanceTypes:
      - t3.large
      maxSize: 2
      minSize: 2
      name: ng-1234
      tags:
        email: akhil@rafay.co
        env: cs-team
      version: "1.30"
      volumeSize: 80
      volumeType: gp3
    metadata:
      name: new-mm-test-cluster
      region: us-west-2
      tags:
        email: akhil@rafay.co
        env: cs-team
      version: "1.30"
    network:
      cni:
        name: aws-cni
    vpc:
      cidr: 192.168.0.0/16
      clusterEndpoints:
        privateAccess: true
        publicAccess: false
      nat:
        gateway: Single
  type: aws-eks
